### ISSUE TITLE
Artefakte im Footer bei linkedIn und Github

### ISSUE THREAD

**Issue by erkules** [erkules/ErkansHomepage#2]
Im Chrome haben wir im Footer bei LinkedIn und Github "Artefakte".
Manometer raffe doch mal was da los ist Erkan!

**Comment by goern** [comment]
just a missing SVG?! https://linsenraum.de/social/github.svg

**Comment by erkules** [comment]
indeed. Versuche zu raffen, warum das Theme es anders macht als in der Doku zu hugo. Weil die beiden (github.svg/linkedin.svg) sind ja unter static/social. Genau wie im original Theme :(

**Comment by erkules** [comment]
Also 
`src="/images/logo.png" ` funzt
und
`src="/social/github.svg" ` nicht.
Beide im static Ordner. 
Naja erst mal pennen <3
